---
apiVersion: v2
name: quality-time
version: v5.48.3
appVersion: "v5.48.3"
description: Helm chart for Quality-time, an automated quality system for software development and maintenance
type: application
home: https://github.com/ICTU/Quality-time
icon: https://raw.githubusercontent.com/ICTU/quality-time/master/docs/src/_static/Quality-time.png
